# -*- coding: utf-8 -*-
"""Chat Agent + Conversational Chat Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ikhf-dsOMEtOD5ZaBiJKtKrapFsRrlWS
"""

!pip install langchain==0.3.24 -q
!pip install langchain-openai -q
!pip install langgraph -q

"""### Chat Agent + Conversational Chat Agent"""

from typing import TypedDict, List
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END

class AgentState(TypedDict):
    messages: List[HumanMessage]

import os
from google.colab import userdata

os.environ['OPENAI_API_KEY'] = ""
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

def chatbot(state: AgentState) -> AgentState:
    response = llm.invoke(state["messages"])
    print(f"\nAI: {response.content}")
    return state

workflow = StateGraph(AgentState)

workflow.add_node("chatbot", chatbot)

workflow.add_edge(START, "chatbot")
workflow.add_edge("chatbot", END)

app = workflow.compile()

from IPython.display import Image, display
display(Image(app.get_graph().draw_mermaid_png()))

user_input = input("Enter a Query: ")
result = app.invoke({"messages": [HumanMessage(content=user_input)]})

user_input = input("Enter a Query: ")
while user_input != "exit":
    result = app.invoke({"messages": [HumanMessage(content=user_input)]})
    user_input = input("Enter a Query: ")



from typing import TypedDict, List , Union
from langchain_core.messages import HumanMessage, AIMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END

class AgentState(TypedDict):
    messages: List[Union[HumanMessage,AIMessage]]

def chatbot(state: AgentState) -> AgentState:
    response = llm.invoke(state["messages"])
    state["messages"].append(AIMessage(content-response.content))
    print(f"\nAI: {response.content}")
    return state

conversation_history = []
user_input = input("Enter a Query: ")
while user_input != "exit":
    conversation_history.append(HumanMessage(content=user_input))
    result = app.invoke({"messages": conversation_history})
    conversation_history = result["messages"]
    user_input = input("Enter a Query: ")
